package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"errors"
	"strings"
	"workbench/graphql-app/graph/model"
	"workbench/graphql-app/middlewares"
)

func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	userAuth := middlewares.GetAuthFromContext(ctx)

	if userAuth.UserID == "0" {
		return nil, errors.New("access denied")
	}

	rows, err := r.Services.Users.ListUsers()
	if err != nil {
		return nil, err
	}

	out := make([]*model.User, 0, len(rows))
	for _, u := range rows {
		out = append(out, badgerUserToGraphUser(u))
	}
	return out, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, term string) ([]model.SearchResult, error) {
	userAuth := middlewares.GetAuthFromContext(ctx)

	if userAuth.UserID == "0" {
		return nil, errors.New("access denied")
	}

	if len(term) == 0 || strings.TrimSpace(term) == "" {
		return []model.SearchResult{}, nil
	}

	var results []model.SearchResult

	// Search Users
	users, err := r.Services.Users.SearchUsersByName(term) // Pas de contexte
	if err != nil {
		return nil, err
	}

	for _, u := range users {
		results = append(results, badgerUserToGraphUser(u))
	}

	return results, nil
}
